### ISSUE TITLE
Cannot run on Goerli without errors

### ISSUE THREAD

**Issue by cryptovestor21** [graphprotocol/AllocationOpt.jl#21]
**Describe the bug**
I have successfully got optimiser working in prod, where indexer-service is on v20.3. I am using my own served network subgraph in all cases.

When I try to run the optimiser against my Goerli testnet instance, running service 20.4, I receive an error back from the service endpoint (logs attached)

**To Reproduce**
1. Run `allocationopt rules "0x7fc17e4faef4893d4311e3d156b59c693e20020c" 5 example.csv 50.0 2 30 0.3 http://localhost:7600/network`
2. With Julia version 'v1.8.2'
3. And installed packages 'Comonicon, allocation'
4. Network subgraph being used on Goerli - `QmPVz18RFwK6hE5rZFWERk23LgrTBz2FCkZzgPSrFxFWN4`
5. Example.csv is blank apart from the titles

**Expected behavior**
I expect a list of recommendations for indexer rule deletions and creations, as per the use of allocationopt on my production graph stack

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22,04

**Additional context**
[allocationopt_output.log](https://github.com/graphprotocol/AllocationOpt.jl/files/9852968/allocationopt_output.log)

**Comment by hopeyen** [comment]
Ah, this was an interesting bug! 😅 

Both mainnet and goerli network subgraph have id of `1` for their protocol chain, so temporarily for this to work, you should pass in `1` whether you are optimizing for mainnet or testnet, and with the right network endpoint. I will make a note to remove this input so you wouldn't need to pass it in anymore. 

A bit on indexer-service's network endpoint, I would just like to make sure that you have set indexer service to serve the network subgraph through its start-up parameter `--serve-network-subgraph true`.

**Comment by cryptovestor21** [comment]
> Ah, this was an interesting bug! 😅
> 
> Both mainnet and goerli network subgraph have id of `1` for their protocol chain, so temporarily for this to work, you should pass in `1` whether you are optimizing for mainnet or testnet, and with the right network endpoint. I will make a note to remove this input so you wouldn't need to pass it in anymore.
> 
> A bit on indexer-service's network endpoint, I would just like to make sure that you have set indexer service to serve the network subgraph through its start-up parameter `--serve-network-subgraph true`.

Thanks Hope :)

This parameter `--serve-network-subgraph true`  - I cannot find a way to pass it to a container as a variable. It doesn't seem to exist as one.

**Comment by hopeyen** [comment]
No problem! 

For context, the parameter is passed into indexer-service package [here](https://github.com/graphprotocol/indexer/blob/fc5dd8fc0cdf1a6ce392d68cab49ffeb2e73c397/packages/indexer-service/src/commands/start.ts#L145) and its significance is [here](https://github.com/graphprotocol/indexer/blob/5a784d8385dfb6cafa19f29b013d5c2a3a244451/packages/indexer-service/src/server/index.ts#L211). I'm not sure which container are you referring to? If it is for indexer repo, I can make an issue there, and temporarily use the gateway network subgraph endpoint

**Comment by cryptovestor21** [comment]
> No problem!
> 
> For context, the parameter is passed into indexer-service package [here](https://github.com/graphprotocol/indexer/blob/fc5dd8fc0cdf1a6ce392d68cab49ffeb2e73c397/packages/indexer-service/src/commands/start.ts#L145) and its significance is [here](https://github.com/graphprotocol/indexer/blob/5a784d8385dfb6cafa19f29b013d5c2a3a244451/packages/indexer-service/src/server/index.ts#L211). I'm not sure which container are you referring to? If it is for indexer repo, I can make an issue there, and temporarily use the gateway network subgraph endpoint

I can't profess to know much about where these vars come from, but if i search for an example one for `INDEXER_SERVICE_INDEXER_ADDRESS` in the repo I find it defined [here](https://github.com/graphprotocol/indexer/blob/0d106091dd51a3f38c0e5b162befbc3157444d08/k8s/base/indexer-service/statefulset.yaml)

Or, for a boolean example like I would imagine `--serve-network-subgraph` should be, [here](https://github.com/graphprotocol/indexer/blob/0d106091dd51a3f38c0e5b162befbc3157444d08/k8s/base/indexer-agent/statefulset.yaml) is a good example.

I really hope this makes sense!

**Comment by hopeyen** [comment]
> > No problem!
> > For context, the parameter is passed into indexer-service package [here](https://github.com/graphprotocol/indexer/blob/fc5dd8fc0cdf1a6ce392d68cab49ffeb2e73c397/packages/indexer-service/src/commands/start.ts#L145) and its significance is [here](https://github.com/graphprotocol/indexer/blob/5a784d8385dfb6cafa19f29b013d5c2a3a244451/packages/indexer-service/src/server/index.ts#L211). I'm not sure which container are you referring to? If it is for indexer repo, I can make an issue there, and temporarily use the gateway network subgraph endpoint
> 
> I can't profess to know much about where these vars come from, but if i search for an example one for `INDEXER_SERVICE_INDEXER_ADDRESS` in the repo I find it defined [here](https://github.com/graphprotocol/indexer/blob/0d106091dd51a3f38c0e5b162befbc3157444d08/k8s/base/indexer-service/statefulset.yaml)
> 
> Or, for a boolean example like I would imagine `--serve-network-subgraph` should be, [here](https://github.com/graphprotocol/indexer/blob/0d106091dd51a3f38c0e5b162befbc3157444d08/k8s/base/indexer-agent/statefulset.yaml) is a good example.
> 
> I really hope this makes sense!

Oh, this helps. I think you might be looking for [INDEXER_SERVICE_SERVE_NETWORK_SUBGRAPH](https://github.com/graphprotocol/indexer/blob/0d106091dd51a3f38c0e5b162befbc3157444d08/k8s/base/indexer-service/statefulset.yaml#L91)?
